services:
  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:7.17.10
    container_name: elasticsearch
    environment:
      - discovery.type=single-node
      - ES_JAVA_OPTS=-Xms1g -Xmx1g
      - xpack.security.enabled=false
    ports:
      - "9200:9200"
    volumes:
      - esdata:/usr/share/elasticsearch/data

  api:
    build:
      context: ./api
    container_name: fastapi_app
    depends_on:
      - elasticsearch
    ports:
      - "8000:8000"
    volumes:
      - /Users/atiliobarreda/Desktop/software/d4bl/switchboard/data  # Mount local PDFs into Docker

  frontend:
    build:
      context: ./frontend
    container_name: nuxt_app
    depends_on:
      - api
    ports:
      - "3000:3000"
    environment:
      - API_BASE_URL=http://api:8000

volumes:
  esdata:
    driver: local
