services:
  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:7.17.10
    container_name: elasticsearch
    environment:
      - discovery.type=single-node
      - ES_JAVA_OPTS=-Xms1g -Xmx1g
      - xpack.security.enabled=false
    ports:
      - "9200:9200"
    volumes:
      - switchboard_data:/usr/share/elasticsearch/data

  api:
    build:
      context: ./api
      dockerfile: Dockerfile
    container_name: switchboard_api
    depends_on:
      - elasticsearch
    ports:
      - "8000:8000"
    volumes:
      - ../data:/app/pdf_data
    environment:
      - PDF_DIRECTORY=/app/pdf_data
      - ELASTICSEARCH_HOST=http://elasticsearch:9200
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8000/health"]
      interval: 30s
      timeout: 10s
      retries: 3

volumes:
  switchboard_data: